# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjQ5NTZmZTQyNmNmYTQyNWI5ZjMzNWJlM2ViOGZjZTJlOGYzNzA2YjMxNWFkMzQzZDIxZmY1NTZiZThmN2MxMzY4MDIxYjk5YjhkNzNlMzE4MzUwN2I2ZTFmZGM5NTczY2MzZGMxYjNmNjQ3YTc1Y2QyNzk2ZTI1ZTBjYmZjOGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
